import React, { FunctionComponent, useState, useCallback } from 'react';
import { TextInput } from 'components/common/TextInput/TextInput';
import './Home.scss';
import { Scheduler } from 'components/Scheduler/Scheduler';

interface HomeProps {}

export const Home: FunctionComponent<HomeProps> = () => {
  // const [coursesInputString, setCoursesInputString] = useState('');
  const [coursesInputString, setCoursesInputString] = useState(
    'CO342, PMATH336, CS466, KOREA101R',
  );
  const [coursesList, setCoursesList] = useState<string[]>([]);

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      setCoursesInputString(event.target.value);
    },
    [],
  );
  const handleKeyPress = useCallback(
    (event: React.KeyboardEvent<HTMLInputElement>) => {
      if (event.key === 'Enter') {
        setCoursesList(coursesInputString.replace(/\s/g, '').split(','));
      }
    },
    [coursesInputString],
  );

  // TODO: add an icon on left of search bar, and maybe an submit button on right?
  return (
    <div className="home">
      <div className="title">
        <h1>uwScheduler</h1>
      </div>
      <div className="search-bar">
        <TextInput
          value={coursesInputString}
          autoFocus={true}
          placeholder={'CO342, CO351, CO454, PMATH336, CS466, KOREA101R'}
          onChange={handleChange}
          onKeyPress={handleKeyPress}
        />
        {coursesList.length && <Scheduler coursesList={coursesList} />}
      </div>
    </div>
  );
};

let temp = [
  [
    {
      subject: 'CO',
      catalog_number: '342',
      units: 0.5,
      title: 'Introduction to Graph Theory',
      note: null,
      class_number: 3641,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 75,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '10:00',
            end_time: '11:20',
            weekdays: 'TTh',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'PHY',
            room: '313',
          },
          instructors: ['Haxell,Penny'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:11-05:00',
    },
  ],
  [
    {
      subject: 'CO',
      catalog_number: '351',
      units: 0.5,
      title: 'Network Flow Theory',
      note: null,
      class_number: 3642,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 75,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '11:30',
            end_time: '12:20',
            weekdays: 'MWF',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'MC',
            room: '2038',
          },
          instructors: ['Pei,Martin'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:11-05:00',
    },
  ],
  [
    {
      subject: 'CO',
      catalog_number: '454',
      units: 0.5,
      title: 'Scheduling',
      note: null,
      class_number: 3643,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '10:00',
            end_time: '11:20',
            weekdays: 'MW',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'MC',
            room: '4064',
          },
          instructors: ['Cheriyan,Joseph'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:11-05:00',
    },
  ],
  [
    {
      subject: 'PMATH',
      catalog_number: '336',
      units: 0.5,
      title: 'Introduction to Group Theory with Applications',
      note: null,
      class_number: 3627,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '08:30',
            end_time: '09:20',
            weekdays: 'MWF',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'MC',
            room: '4021',
          },
          instructors: ['Madill,Blake'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:43-05:00',
    },
  ],
  [
    {
      subject: 'CS',
      catalog_number: '466',
      units: 0.5,
      title: 'Algorithm Design and Analysis',
      note: null,
      class_number: 3659,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: '101',
      related_component_2: null,
      enrollment_capacity: 60,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '11:30',
            end_time: '12:50',
            weekdays: 'MW',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'RCH',
            room: '308',
          },
          instructors: ['Lau,Lap Chi'],
        },
      ],
      held_with: ['CS 666'],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:18-05:00',
    },
    {
      subject: 'CS',
      catalog_number: '466',
      units: 0.5,
      title: 'Algorithm Design and Analysis',
      note: null,
      class_number: 5365,
      section: 'LEC 002',
      campus: 'UW U',
      associated_class: 2,
      related_component_1: '101',
      related_component_2: null,
      enrollment_capacity: 60,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '13:00',
            end_time: '14:20',
            weekdays: 'MW',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'RCH',
            room: '308',
          },
          instructors: ['Lau,Lap Chi'],
        },
      ],
      held_with: ['CS 666'],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:18-05:00',
    },
    {
      subject: 'CS',
      catalog_number: '466',
      units: 0.5,
      title: 'Algorithm Design and Analysis',
      note: null,
      class_number: 4079,
      section: 'TST 101',
      campus: 'UW U',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 120,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '19:00',
            end_time: '20:50',
            weekdays: 'W',
            start_date: '06/17',
            end_date: '06/17',
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: null,
            room: null,
          },
          instructors: [],
        },
      ],
      held_with: ['CS 666'],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:18-05:00',
    },
  ],
  [
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4117,
      section: 'LEC 001',
      campus: 'REN R',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '13:00',
            end_time: '14:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2107',
          },
          instructors: ['Kim,Young Gon'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4132,
      section: 'LEC 002',
      campus: 'REN R',
      associated_class: 2,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '14:30',
            end_time: '15:50',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2107',
          },
          instructors: ['Kim,Young Gon'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4140,
      section: 'TUT 101',
      campus: 'REN R',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 30,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '16:00',
            end_time: '17:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2107',
          },
          instructors: ['Kang,Youngoak'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4141,
      section: 'TUT 102',
      campus: 'REN R',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 30,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '16:00',
            end_time: '17:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2102',
          },
          instructors: ['Cho,Grace'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4142,
      section: 'TUT 103',
      campus: 'REN R',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 30,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '18:00',
            end_time: '19:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2102',
          },
          instructors: ['Kim,Wonhee'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
  ],
];

const temp2 = [
  [
    {
      subject: 'CO',
      catalog_number: '342',
      units: 0.5,
      title: 'Introduction to Graph Theory',
      note: null,
      class_number: 3641,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 75,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '10:00',
            end_time: '11:20',
            weekdays: 'TTh',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'PHY',
            room: '313',
          },
          instructors: ['Haxell,Penny'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:11-05:00',
    },
  ],
  [
    {
      subject: 'CO',
      catalog_number: '351',
      units: 0.5,
      title: 'Network Flow Theory',
      note: null,
      class_number: 3642,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 75,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '11:30',
            end_time: '12:20',
            weekdays: 'MWF',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'MC',
            room: '2038',
          },
          instructors: ['Pei,Martin'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:11-05:00',
    },
  ],
  [
    {
      subject: 'CO',
      catalog_number: '454',
      units: 0.5,
      title: 'Scheduling',
      note: null,
      class_number: 3643,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '10:00',
            end_time: '11:20',
            weekdays: 'MW',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'MC',
            room: '4064',
          },
          instructors: ['Cheriyan,Joseph'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:11-05:00',
    },
  ],
  [
    {
      subject: 'PMATH',
      catalog_number: '336',
      units: 0.5,
      title: 'Introduction to Group Theory with Applications',
      note: null,
      class_number: 3627,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '08:30',
            end_time: '09:20',
            weekdays: 'MWF',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'MC',
            room: '4021',
          },
          instructors: ['Madill,Blake'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:43-05:00',
    },
  ],
  [
    {
      subject: 'CS',
      catalog_number: '466',
      units: 0.5,
      title: 'Algorithm Design and Analysis',
      note: null,
      class_number: 3659,
      section: 'LEC 001',
      campus: 'UW U',
      associated_class: 1,
      related_component_1: '101',
      related_component_2: null,
      enrollment_capacity: 60,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '11:30',
            end_time: '12:50',
            weekdays: 'MW',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'RCH',
            room: '308',
          },
          instructors: ['Lau,Lap Chi'],
        },
      ],
      held_with: ['CS 666'],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:18-05:00',
    },
    {
      subject: 'CS',
      catalog_number: '466',
      units: 0.5,
      title: 'Algorithm Design and Analysis',
      note: null,
      class_number: 5365,
      section: 'LEC 002',
      campus: 'UW U',
      associated_class: 2,
      related_component_1: '101',
      related_component_2: null,
      enrollment_capacity: 60,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '13:00',
            end_time: '14:20',
            weekdays: 'MW',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'RCH',
            room: '308',
          },
          instructors: ['Lau,Lap Chi'],
        },
      ],
      held_with: ['CS 666'],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:18-05:00',
    },
    {
      subject: 'CS',
      catalog_number: '466',
      units: 0.5,
      title: 'Algorithm Design and Analysis',
      note: null,
      class_number: 4079,
      section: 'TST 101',
      campus: 'UW U',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 120,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '19:00',
            end_time: '20:50',
            weekdays: 'W',
            start_date: '06/17',
            end_date: '06/17',
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: null,
            room: null,
          },
          instructors: [],
        },
      ],
      held_with: ['CS 666'],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:09:18-05:00',
    },
  ],
  [
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4117,
      section: 'LEC 001',
      campus: 'REN R',
      associated_class: 1,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '13:00',
            end_time: '14:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2107',
          },
          instructors: ['Kim,Young Gon'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4132,
      section: 'LEC 002',
      campus: 'REN R',
      associated_class: 2,
      related_component_1: null,
      related_component_2: null,
      enrollment_capacity: 45,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '14:30',
            end_time: '15:50',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2107',
          },
          instructors: ['Kim,Young Gon'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4140,
      section: 'TUT 101',
      campus: 'REN R',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 30,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '16:00',
            end_time: '17:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2107',
          },
          instructors: ['Kang,Youngoak'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4141,
      section: 'TUT 102',
      campus: 'REN R',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 30,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '16:00',
            end_time: '17:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2102',
          },
          instructors: ['Cho,Grace'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
    {
      subject: 'KOREA',
      catalog_number: '101R',
      units: 0.5,
      title: 'First-Year Korean 1',
      note: 'Choose TUT section for Related 1.',
      class_number: 4142,
      section: 'TUT 103',
      campus: 'REN R',
      associated_class: 99,
      related_component_1: '99',
      related_component_2: null,
      enrollment_capacity: 30,
      enrollment_total: 0,
      waiting_capacity: 0,
      waiting_total: 0,
      topic: null,
      reserves: [],
      classes: [
        {
          date: {
            start_time: '18:00',
            end_time: '19:20',
            weekdays: 'W',
            start_date: null,
            end_date: null,
            is_tba: false,
            is_cancelled: false,
            is_closed: false,
          },
          location: {
            building: 'REN',
            room: '2102',
          },
          instructors: ['Kim,Wonhee'],
        },
      ],
      held_with: [],
      term: 1205,
      academic_level: 'undergraduate',
      last_updated: '2020-03-07T02:10:03-05:00',
    },
  ],
];
